version: "3.8"

services:
  web-rails:
    user: "0:0"
    build:
      context: .
      dockerfile: ./config/dockerfiles/Dockerfile-ruby
      args:
        IMG_VERSION: "3.1.2"
        RAILS_VERSION: "7.0.4"
        APT_FILE: "web-rails"
        NPM_FILE: "web-rails"
        NODE_VERSION: '16'
    ports:
      - "3000:3000"
    env_file:
      - ./config/environments/.backend.development.env
      - ./config/environments/.db.development.env
    logging:
      driver: "json-file"
    volumes:
      - ~/.ssh:/home/rails/.ssh
      - ./services/web-rails:/app
      - bundler_gems:/usr/local/bundle/
    depends_on:
      - db-postgres
    stdin_open: true
    tty: true
    #   to run with byebug:
    #   docker-compose up -d && docker attach groundzero_api-rails_1
    command: bash -c "bundle check || bundle install --without production && rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
  db-postgres:
    image: postgres:14.5
    restart: always
    ports:
      - 3001:5432
    logging:
      driver: "none"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    env_file:
      - ./config/environments/.db.development.env
  db-admin:
    image: adminer
    restart: always
    ports:
      - 3002:8080
    logging:
      driver: "none"
    depends_on:
      - db-postgres
volumes:
  db-postgres: {}
  bundler_gems: {}
