ARG IMG_VERSION
FROM ruby:$IMG_VERSION

ARG INSTALL_PATH=/app
ARG LOCAL_USER=rails

ARG RAILS_VERSION
ARG NODE_VERSION
ARG APT_FILE
ARG NPM_FILE

ARG UID
ARG GID

RUN apt-get update -qq && apt-get install -y build-essential sudo

# Additional Packages - aptfile
COPY ./config/apt-files/. /apt-files
RUN if [ -n "$APT_FILE" ] ; then \
  apt-get install -yq $(grep -Ev '^\s*#' /apt-files/${APT_FILE} | xargs) ; \
fi

# Nodejs
RUN if [ -n "$NODE_VERSION" ] ; then \
  curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - && apt-get install -y nodejs ; \
fi

# NPM
COPY ./config/npm-files/. /npm-files
RUN if [ -n "$NPM_FILE" ] ; then \
  npm install --force -g $(grep -Ev '^\s*#' /npm-files/${NPM_FILE} | xargs) ; \
fi

# Change directory so that our commands run inside this new directory
WORKDIR $INSTALL_PATH

# Create local user
RUN useradd -u $UID -g $GID -m $LOCAL_USER && echo "${LOCAL_USER}:${LOCAL_USER}" | chpasswd && adduser $LOCAL_USER sudo
RUN passwd -d $LOCAL_USER
RUN usermod -a -G users $LOCAL_USER

RUN touch /var/lib/sudo/lectured/rails

USER $LOCAL_USER

# Rails
RUN if [ -n "$RAILS_VERSION" ] ; then \
  gem install rails -v=$RAILS_VERSION --no-document ; \
fi

CMD ["bundle", "exec", "rails", "server"]
