FROM node:18.15.0

ARG LOCAL_USER=node

# NPM
RUN npm install --force -g npm@9.6.3 yarn

# Change directory so that our commands run inside this new directory
WORKDIR /app

# Install global packages with local user
USER $LOCAL_USER

CMD ["npm", "run", "start"]
