FROM node:16.13.1

# required to be passed in
ENV APP_PATH=./services/web-react
ENV INSTALL_PATH=/app
ENV LOCAL_USER=node

# Create a directory where our app will be placed
RUN mkdir -p ${INSTALL_PATH}

# Change directory so that our commands run inside this new directory
WORKDIR $INSTALL_PATH

# Install global packages with local user
USER $LOCAL_USER

# Get all the code needed to run the app
COPY $APP_PATH/. $INSTALL_PATH/.

CMD ["npm", "run", "start"]
