# TODO change to ruby 3.1.0 as soon as rails is 7.0.1
FROM ruby:3.0.0
RUN apt-get update -qq && apt-get install -y build-essential vim sudo

# Nodejs
# RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
#     apt-get install -y nodejs

# required to be passed in
ENV INSTALL_PATH=/app
ENV LOCAL_USER=rails

# Change directory so that our commands run inside this new directory
WORKDIR $INSTALL_PATH

# Create local user
RUN useradd -m $LOCAL_USER && echo "${LOCAL_USER}:${LOCAL_USER}" | chpasswd && adduser $LOCAL_USER sudo
RUN usermod -a -G users $LOCAL_USER
USER $LOCAL_USER

RUN gem install rails -v=7.0.0 --no-document

# RUN bundle install

CMD ["bundle", "exec", "rails", "server"]
