ARG IMG_VERSION
FROM ruby:$IMG_VERSION

ARG INSTALL_PATH=/app

ARG RAILS_VERSION
ARG NODE_VERSION
ARG APT_FILE
ARG NPM_FILE

RUN apt-get update -qq && apt-get install -y build-essential

# Additional Packages - aptfile
COPY ./config/apt-files/. /apt-files
RUN if [ -n "$APT_FILE" ] ; then \
  apt-get install -yq $(grep -Ev '^\s*#' /apt-files/${APT_FILE} | xargs) ; \
fi

# Nodejs
RUN if [ -n "$NODE_VERSION" ] ; then \
  curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - && apt-get install -y nodejs ; \
fi

# NPM
COPY ./config/npm-files/. /npm-files
RUN if [ -n "$NPM_FILE" ] ; then \
  npm install --force -g $(grep -Ev '^\s*#' /npm-files/${NPM_FILE} | xargs) ; \
fi

# Change directory so that our commands run inside this new directory
WORKDIR $INSTALL_PATH

# acknowledge sudo warning
RUN touch /var/lib/sudo/lectured/rails

# Rails
RUN if [ -n "$RAILS_VERSION" ] ; then \
  gem install rails -v=$RAILS_VERSION --no-document ; \
fi

CMD ["bundle", "exec", "rails", "server"]
